language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console

script:
  - xbuild source/Cucumber.SimpleDb.sln
  - nunit-console source/Cucumber.SimpleDb.Test/Debug/Cucumber.SimpleDb.Test.dll
notifications:
  email:
    - rex@rexmorgan.net