language: c

before_install:
  - export EnableNuGetPackageRestore=true

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console

script:
  - xbuild /p:Configuration=Release source/Cucumber.SimpleDb.sln
  - nunit-console source/Cucumber.SimpleDb.Test/bin/Release/Cucumber.SimpleDb.Test.dll

notifications:
  email:
    - rex@rexmorgan.net