language: c

before_script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash build/SetupSSH.sh'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash build/GitSetup.sh'
  - 'source build/SetBuildNumber.sh'
  - '[ "${TRAVIS_BRANCH}" = "master" ] && source PushBuildNumber.sh'
  - 'bash build/SetAssemblyVersion.sh'

install:
  - sudo add-apt-repository ppa:directhex/monoxide -y && sudo apt-get update
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - mozroots --import --sync

script:
  - xbuild /p:Configuration=Release source/Cucumber.SimpleDb.sln
  - nunit-console source/Cucumber.SimpleDb.Test/bin/Release/Cucumber.SimpleDb.Test.dll
  
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash build/CommitUpdatedAssembly.sh'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash build/PublishNuGetPackage.sh'
  
notifications:
  email:
    - rex@rexmorgan.net

env:
  global:
    - EnableNuGetPackageRestore=true
    # NuGet
    - secure: "ncQSFClG5yQKJjNX14DkxKmOW6Wirh6dT0JCLiwFCos/WaSRngVPXnZu1rjojb2JA9iAjtd0A3HR6GXi24/1U8b8gBCykHGnN6iRH2WumnPEdY2cb0VM0T4oQqRna3e0HZGJUH7qz0grVqAS4mrsZVVCOVyVLQEe8rmeU9RWsCM="
    # SSH
    - secure: "W4ZSAojMFLIxl0K33vGAs0WnKN/xZeRznu9cgIxl10PYylt8RtwXdvhXvHOU2QI1igDl6imCQi+Xn7zK3Rtf2n5kkP6X3l0QZVSNklV5W73tA8QTBPKV4NUMauEjT/PgZfNnmwBFkHOviGkyuvIuC0iHMfGx5ldHhYkv4TCCdEM="
    - secure: "MPqyKBcZUZFs7jJgiUHKjpYb3bBaZkjqGSVu3nSqg8vL9fLc5NGcxSZHaercKvoqI98R4xn0ubirxSPCKfvOceYz4VamEcnVR34GUnSFzKINToJgI10hEcgYCj9H0mb/3/xk/atxnYP79ST4W/a3DEB/LprJvR/HAGCSTF6gUqE="
    - secure: "wa+Nn8JWtF8nPky+HAsewuXfRtjCmwSsTUuTqby2dm2ANo1vUSt+Dug13IkbO68R45VjMqnymrHr5h4ucCIx5A3wkn2SdG7U1DqJ8Av/Mmr1iTmb5jwkUe76tQXMMH2xXhZI08NvQF/2DDmXFlE6O9GABoS3C6hIYhmeOm065SA="
    - secure: "l3Vi9Ihdz7q8f62rVIN0asC0SD2jhjy2F3b/PHIg4Xq12INMzbJz3dvTNRR8G2B+NWaj9q6x2MuJK2179SJsdz0vhLUbxDTn8iPGnXwZBbs+ZqRATKBCQ0DgsQBz2NCSoQ8FwaxFDfyvsocsWPtAnNu4/tLq+wY9tFk7x1i4AEg="
    - secure: "t7mf6FVfITckU+vZEg/oAciDPSrrQcYSAxCQRgME9ka+ZhtaZkLyHCHW6/QHUb+/OGvApiuMb6Ed8m0ZJnmEWBbiapqE6HcQSwsd5b2oFVtmoU4BgFQWPeDmaky0a3e6z1bNEYbBtW43mtZ6HMz+n2VBqpW0RDRyJ8dfWIkr5oQ="
    - secure: "TICdzCCZKyDg1eSeO2SJCvQUxS0NBYMUOgf04uJn8xA2lPYAOJzxmaX7rE9vLb5I61ESRzNoo8QwC3qlvesVXooa3skvh+PUsiDZnOy+rH9qjgnYeETl48he7YzE/0l1KtLGXmenD3SiUMjyjese0a6LUu6JMRHsZFZTuEyOAuA="
    - secure: "O6T7GB98PDhOYySH6HS6v6QbxB+aSq6CyM8A45GEJwf50e0idcveYJlXbFcvQQ4ftgnp+LyNecda+ncgqWia/4LM9tzg1PG8WPV85tK9UJ7Cvy/NSfKLG33GKbt6DJvZ7FDgAcq5Jr0lgrJ8HZsZSKp8ogfnvDnBLcA4K1Av81c="
    - secure: "wZ40dUi0oQB2U56GJ1AUjfGZq8u2O01hXQcIAUtIh9k5JMIDJLmCjxc9kmVCfJErmd6skeAjg2NRxzqRpVaJohm6egNTM831ko8lrdajalb2WCqWwahgphbRa9rBIIv5zP8gEw74GKKtKc/gLyL3i37O6JniNMeONtlsR7H2YA4="
    - secure: "VqnWdqAvi64OfCVu0KsKFZVLbnzSkHB9ZTc3eEhE47IbfgMwVfFo8UmqxJozknd60yNokSrtUVn9TJIffSXosNzMXeLBtWxJ6MOoLT8xOJIUUjvTckhlld2wibmYNnAJWCw5fqtxZKHDazeD7xt4F3nnCOrqR00WgbIwFWqxm94="
    - secure: "tSWnFwsF+zW3ZlIFoQl6QLnjWQMPKPIDA9tuBbHW6G983QXMzu55AWKs3BeM0y1vbJWRxlTluYDI6ZlzGgYiCJYO0URVuLRQwhW4EchnipfWCvV5miexZMza4lsMhg5iOYr+b7LXc1kGVH7gb0QTo/wbA1YI2YuaKihxVVuC2L0="
    - secure: "MJAydhMB+bDeMPX5UzQnYsDeT1KEeFNPfq5UyVOK4g/n7iLSm+cc38uSDctOecyMq/tJShl6GqDwzePh4Q2/GUU55wCu7Cugh3HwO6XizbV1ZhA7k1m7veGlij98MyRcyoAUQJ15RUahv5CQqJiMcwabaY8tO3RCdxl3Tx16p4k="
    - secure: "jdhOFdwDiNNPkkUd7UKBI0PKtbFeLfUGJrVpd3oDxcHI4DViA1ZlnXDHe7V3Qh1ml9+ToXc21EqkfW5zLArP1qqTNZMAFDNTa5mdDaVDX0/Y9o+nul0+SbuOwt5LdxTbr7ks887+ytcdnqBkpmIWXYv0dCeSVzzGhSBHmlZqigs="
    - secure: "n8gipqQ82c2qOiD4NxoWE3P6Tb8MU9ZfQYwHjBVxqMKdg3W/MGh3t8EXTLs68UOKHQMOdpQOeviAp4YzNPgbLMGEIIyDDxL1Ls1U6qEBElsJ2Yph2H7yYxQc3xR3wus2v/uaY485cCeMgLec7zXk2avomlrZ8WMHrjWHh5Wi8gA="
    - secure: "mgV8yYlQCWnxJdQE6FsBC/RFCHDy7anjFl0rsety783TAbf5AILIQLMWrr9U0PN+5ikhBJmyIXnBH1o18SY8CCybLHAJI0Fw618OnCHGsKe6YySbu0PKwQLoM8So8dCC0PMldvXRaHPJki7l9eyDbO/dA4h4ltMBlBua6u/LWek="
    - secure: "d+iSeP7FE8BqTNM/f25nbz2xDeEKijiObiAX8Q6C4QiugEx8O/2m0QmtxJR3sn/duxZXBi2uJkePhfN4suJtIVOoiuQ07eMk0fJGhBueJ3nSGGS8ye+FQpDvXCIkgg/q93ABOt9IAeNJKJEzE7Rt3lrIc/PCkguctG+tNhB1PQc="
    - secure: "pz2aHxBgo8gSekVdQkXyInfqT2jIqTNhgsmXA4I+O1ndQCPLix3aevNGT000BlcVjHIY4YvxtSBZON0ecvJiIhfMnkpNyqWBshrbebguBWo7xF3cdj2Qrj1UAr6IIX60YGoRXfn6PueCwC9jcVPsRQ2yf9wzWWOWotHVV+uQRfI="
    - secure: "Ldsf1Fki+rhvPlwaVbPpWdWymjV60SU4cmvV1voaFVCcWDmA3JevFqtB35qJ9sxLWDUa1pDL52LEUiMmitBI59dQJ8YWlgGrjSGVxa7F1TY32bXqOeCnOEusOM6BtE7kEFAaE7UkaLKQL2titpeC1+B1aDaZ2YsJjikST5RcfNc="
    - secure: "Hv0KCkHCnejjcn4LlQIqLTWjcgfKZrVAiV+xls9f7Tpa6xsJjHUY7AfnAUAa0j5CjcRCc9Yy4zZ7bUwqYnAFCc7Yibn0I4L2JkMAAxckb7ows8l2qgUTsHhp539mj7Ntjt21jL/Dpkuc1Q4ZhpPuP6uP0y54RAdRlLyqKZMNtpw="
    - secure: "GdShyDgq9EXW7Byz6vFi1hSlGl+RZhIbakEDnarYkA9YywMEvfbIKhePJDhekC3r6E0VU+0KdPijKzoq5GSH6dL/PWAvLHHQnJJ3+tNOjEyF/FNLGr5077hLvtRwVHbL0NnmFR0JMH8WEDJkQNI3RfaSW3DrQ6QxaP2lPX+KSUg="
    - secure: "ncllKd9JEMZDyRFAtWzuwiBUC6savri3BzNt1Am3livZfyTNGr6dVdqpftRfCCsRNB2ChQNdy11qmSd0wJ1JeQ4naDtXu6E/5dB2pVnVX4Lo9aO9NQerKsXeL9cg+MK0VjAarFtsAc5BpYYEuBAY5JHr+PQStsr36e/Wy8Q7HPo="
    - secure: "JKanv1QLHxR58Ys1SDsZzx/0ed6wUN+wNDWhabzY0ZVBaapV9WZzd8REFBMYEY+zI3yHxHfvjI9dh+pLX2Rsg/6dd7bBs2+eAu6CsiAQOSPXhUAQ4dxwxeDtsPhqUZBiBsAgWoByvG/fxa30RaOO1y4e6L74P6EqsGQMG3bZg0w="
    - secure: "n2x/MCgW6FFPEUjSCt8/GF3S32q7ks4ccEvNWc066+cqtQZ7SqeRcGPvTE+47dDq3Ft1pVxtCLmUfRlabx/OYmdFvGQyJAestBbnAH0x16AKixCMTzIPc1cgBkXEsiTSmPXGAq08mX/lRbZaNgeL9TLXXyDB4dTSxfaGAlKfcxQ="
    - secure: "OVgL6EsDWIsxq7MGNi7fochcZp+TfjOrgE03J8nkb1XI4hOLmTRzu9Mq9C68P17XdMpH4FPzWmEVXtMDPlexIZCI+OnpfJvcFmEEVxS5yK1KXDmpeJTsuEOQjmUGv7aS9hHse5boABbr+E731xPcuSBBF4hP4hQUqGEb1fayNX0="
