language: c

before_install:
  - export EnableNuGetPackageRestore=true

install:
  - sudo add-apt-repository ppa:directhex/monoxide -y && sudo apt-get update
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - mozroots --import --sync

script:
  - xbuild /p:Configuration=Release source/Cucumber.SimpleDb.sln
  - nunit-console source/Cucumber.SimpleDb.Test/bin/Release/Cucumber.SimpleDb.Test.dll

notifications:
  email:
    - rex@rexmorgan.net
